# Generated by Django 5.1.1 on 2024-09-10 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0002_barberia_servicio_remove_payment_appointment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='barberia',
        ),
        migrations.RemoveField(
            model_name='barberface',
            name='cliente',
        ),
        migrations.AddField(
            model_name='barberface',
            name='barbero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='barbershop.barbero'),
        ),
        migrations.AddField(
            model_name='promociones',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='promociones/'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicios/'),
        ),
        migrations.DeleteModel(
            name='DetalleContabilidad',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
    ]
